//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedRess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("web.Resources.Views.Shared.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string aboutus {
            get {
                return ResourceManager.GetString("aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Bilgileri ve Google Map.
        /// </summary>
        public static string addressandgooglemap {
            get {
                return ResourceManager.GetString("addressandgooglemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylı Arama.
        /// </summary>
        public static string advancedsearch {
            get {
                return ResourceManager.GetString("advancedsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danışmanlarımız.
        /// </summary>
        public static string advisors {
            get {
                return ResourceManager.GetString("advisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümü.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Bilgileri.
        /// </summary>
        public static string bankaccounts {
            get {
                return ResourceManager.GetString("bankaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka.
        /// </summary>
        public static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brifingler.
        /// </summary>
        public static string brifing {
            get {
                return ResourceManager.GetString("brifing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bina Yaşı.
        /// </summary>
        public static string buildingage {
            get {
                return ResourceManager.GetString("buildingage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kariyer Olanakları.
        /// </summary>
        public static string careeropportunities {
            get {
                return ResourceManager.GetString("careeropportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merkez Ofis.
        /// </summary>
        public static string centeroffice {
            get {
                return ResourceManager.GetString("centeroffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sertifikalarımız.
        /// </summary>
        public static string certificates {
            get {
                return ResourceManager.GetString("certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamamlanmış Projeler.
        /// </summary>
        public static string completedprojects {
            get {
                return ResourceManager.GetString("completedprojects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri.
        /// </summary>
        public static string contactdetails {
            get {
                return ResourceManager.GetString("contactdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Formu.
        /// </summary>
        public static string contactform {
            get {
                return ResourceManager.GetString("contactform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize Ulaşın.
        /// </summary>
        public static string contactus {
            get {
                return ResourceManager.GetString("contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm hakları saklıdır, Copyright 2014..
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string culture {
            get {
                return ResourceManager.GetString("culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string culturename {
            get {
                return ResourceManager.GetString("culturename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        public static string district {
            get {
                return ResourceManager.GetString("district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÖKÜMANLAR.
        /// </summary>
        public static string documents {
            get {
                return ResourceManager.GetString("documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekipmanlarımız.
        /// </summary>
        public static string equipments {
            get {
                return ResourceManager.GetString("equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gayrimenkul Danışmanı.
        /// </summary>
        public static string estateconsultant {
            get {
                return ResourceManager.GetString("estateconsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü.
        /// </summary>
        public static string estatetype {
            get {
                return ResourceManager.GetString("estatetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzmanlık Alanlarımız.
        /// </summary>
        public static string expertise {
            get {
                return ResourceManager.GetString("expertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öne Çıkan Gayrimenkuller.
        /// </summary>
        public static string featuredproperties {
            get {
                return ResourceManager.GetString("featuredproperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmalar ve Markalar.
        /// </summary>
        public static string firmsandbrands {
            get {
                return ResourceManager.GetString("firmsandbrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurucular ve Yönetim.
        /// </summary>
        public static string founders {
            get {
                return ResourceManager.GetString("founders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Dön.
        /// </summary>
        public static string goback {
            get {
                return ResourceManager.GetString("goback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiralık.
        /// </summary>
        public static string hired {
            get {
                return ResourceManager.GetString("hired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANASAYFA.
        /// </summary>
        public static string homepage {
            get {
                return ResourceManager.GetString("homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konut.
        /// </summary>
        public static string housing {
            get {
                return ResourceManager.GetString("housing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnsan Kaynakları.
        /// </summary>
        public static string humanresources {
            get {
                return ResourceManager.GetString("humanresources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KURUMSAL.
        /// </summary>
        public static string institutional {
            get {
                return ResourceManager.GetString("institutional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arsa.
        /// </summary>
        public static string land {
            get {
                return ResourceManager.GetString("land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brifing Bırakın, Geri Dönelim.
        /// </summary>
        public static string leaveyourbrief {
            get {
                return ResourceManager.GetString("leaveyourbrief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAĞLANTILAR.
        /// </summary>
        public static string links {
            get {
                return ResourceManager.GetString("links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt.
        /// </summary>
        public static string locality {
            get {
                return ResourceManager.GetString("locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harita.
        /// </summary>
        public static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piyasa Analizleri / Sektörden Haberler.
        /// </summary>
        public static string marketnews {
            get {
                return ResourceManager.GetString("marketnews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hakkimizda.
        /// </summary>
        public static string menu_aboutus {
            get {
                return ResourceManager.GetString("menu_aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detayli-arama.
        /// </summary>
        public static string menu_advancedsearch {
            get {
                return ResourceManager.GetString("menu_advancedsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tum-haberler.
        /// </summary>
        public static string menu_allnews {
            get {
                return ResourceManager.GetString("menu_allnews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basvuru.
        /// </summary>
        public static string menu_application {
            get {
                return ResourceManager.GetString("menu_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banka-hesaplari.
        /// </summary>
        public static string menu_bankaccounts {
            get {
                return ResourceManager.GetString("menu_bankaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kariyer.
        /// </summary>
        public static string menu_career {
            get {
                return ResourceManager.GetString("menu_career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sertifikalar.
        /// </summary>
        public static string menu_certificates {
            get {
                return ResourceManager.GetString("menu_certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tamamlanan-projeler.
        /// </summary>
        public static string menu_completedprojects {
            get {
                return ResourceManager.GetString("menu_completedprojects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iletisim-bilgileri.
        /// </summary>
        public static string menu_contactdetails {
            get {
                return ResourceManager.GetString("menu_contactdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iletisim-formu.
        /// </summary>
        public static string menu_contactform {
            get {
                return ResourceManager.GetString("menu_contactform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        public static string menu_culture {
            get {
                return ResourceManager.GetString("menu_culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dokumanlar.
        /// </summary>
        public static string menu_documents {
            get {
                return ResourceManager.GetString("menu_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ekipmanlar.
        /// </summary>
        public static string menu_equipments {
            get {
                return ResourceManager.GetString("menu_equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anasayfa.
        /// </summary>
        public static string menu_homepage {
            get {
                return ResourceManager.GetString("menu_homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insan-kaynaklari.
        /// </summary>
        public static string menu_humanresources {
            get {
                return ResourceManager.GetString("menu_humanresources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hakkimizda.
        /// </summary>
        public static string menu_institutional {
            get {
                return ResourceManager.GetString("menu_institutional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linkler.
        /// </summary>
        public static string menu_links {
            get {
                return ResourceManager.GetString("menu_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to haberler.
        /// </summary>
        public static string menu_news {
            get {
                return ResourceManager.GetString("menu_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teklif.
        /// </summary>
        public static string menu_offer {
            get {
                return ResourceManager.GetString("menu_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devam-eden-projeler.
        /// </summary>
        public static string menu_ongoingprojects {
            get {
                return ResourceManager.GetString("menu_ongoingprojects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basinda-biz.
        /// </summary>
        public static string menu_onpress {
            get {
                return ResourceManager.GetString("menu_onpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acik-pozisyonlar.
        /// </summary>
        public static string menu_openpositions {
            get {
                return ResourceManager.GetString("menu_openpositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hizmetlerimiz.
        /// </summary>
        public static string menu_ourservices {
            get {
                return ResourceManager.GetString("menu_ourservices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ekibimiz.
        /// </summary>
        public static string menu_ourteam {
            get {
                return ResourceManager.GetString("menu_ourteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urun-detay.
        /// </summary>
        public static string menu_productdetail {
            get {
                return ResourceManager.GetString("menu_productdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urunler.
        /// </summary>
        public static string menu_products {
            get {
                return ResourceManager.GetString("menu_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projeler.
        /// </summary>
        public static string menu_projects {
            get {
                return ResourceManager.GetString("menu_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to referanslar.
        /// </summary>
        public static string menu_references {
            get {
                return ResourceManager.GetString("menu_references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detayli-arama.
        /// </summary>
        public static string menu_searchestate {
            get {
                return ResourceManager.GetString("menu_searchestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sektorler.
        /// </summary>
        public static string menu_sectors {
            get {
                return ResourceManager.GetString("menu_sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hizmetler.
        /// </summary>
        public static string menu_services {
            get {
                return ResourceManager.GetString("menu_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cozum-ortaklari.
        /// </summary>
        public static string menu_solutionpartners {
            get {
                return ResourceManager.GetString("menu_solutionpartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vizyon-misyon.
        /// </summary>
        public static string menu_visionmision {
            get {
                return ResourceManager.GetString("menu_visionmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neden-biz.
        /// </summary>
        public static string menu_whyus {
            get {
                return ResourceManager.GetString("menu_whyus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one-cikan-gayrimenkuller.
        /// </summary>
        public static string menupopularestates {
            get {
                return ResourceManager.GetString("menupopularestates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misyonumuz.
        /// </summary>
        public static string mision {
            get {
                return ResourceManager.GetString("mision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daha fazlası....
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha büyük görüntüle.
        /// </summary>
        public static string morebig {
            get {
                return ResourceManager.GetString("morebig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Listem.
        /// </summary>
        public static string myofferlist {
            get {
                return ResourceManager.GetString("myofferlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haberler.
        /// </summary>
        public static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haber Detayı.
        /// </summary>
        public static string newsdetail {
            get {
                return ResourceManager.GetString("newsdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam Eden Projeler.
        /// </summary>
        public static string ongoingprojects {
            get {
                return ResourceManager.GetString("ongoingprojects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basında Venue İstanbul.
        /// </summary>
        public static string onpress {
            get {
                return ResourceManager.GetString("onpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açık Pozisyonlar.
        /// </summary>
        public static string openpositions {
            get {
                return ResourceManager.GetString("openpositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer Faaliyetlerimiz.
        /// </summary>
        public static string otheroperations {
            get {
                return ResourceManager.GetString("otheroperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biz.
        /// </summary>
        public static string our {
            get {
                return ResourceManager.GetString("our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşterilerimiz.
        /// </summary>
        public static string ourcustomers {
            get {
                return ResourceManager.GetString("ourcustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİZDEN HABERLER.
        /// </summary>
        public static string ournews {
            get {
                return ResourceManager.GetString("ournews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetlerimiz.
        /// </summary>
        public static string ourservices {
            get {
                return ResourceManager.GetString("ourservices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekibimiz.
        /// </summary>
        public static string ourteam {
            get {
                return ResourceManager.GetString("ourteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KONTROLMATİK.
        /// </summary>
        public static string pagetitle {
            get {
                return ResourceManager.GetString("pagetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Seçiniz.
        /// </summary>
        public static string pleaseselect {
            get {
                return ResourceManager.GetString("pleaseselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öne Çıkan Gayrimenkuller.
        /// </summary>
        public static string popularestates {
            get {
                return ResourceManager.GetString("popularestates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat Aralığı.
        /// </summary>
        public static string pricerange {
            get {
                return ResourceManager.GetString("pricerange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kodu.
        /// </summary>
        public static string product_code {
            get {
                return ResourceManager.GetString("product_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Detayı.
        /// </summary>
        public static string projectedetail {
            get {
                return ResourceManager.GetString("projectedetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projelerimiz.
        /// </summary>
        public static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans No.
        /// </summary>
        public static string referenceno {
            get {
                return ResourceManager.GetString("referenceno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referanslar.
        /// </summary>
        public static string references {
            get {
                return ResourceManager.GetString("references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurucularımızın uzun iş hayatı boyunca hizmet verdiği firma ve markalardan bazıları.....
        /// </summary>
        public static string referencestext {
            get {
                return ResourceManager.GetString("referencestext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen gerekli alanları eksiksiz ve doğru bir şekilde doldurunuz.
        /// </summary>
        public static string requiredfields {
            get {
                return ResourceManager.GetString("requiredfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Sayısı.
        /// </summary>
        public static string roomcount {
            get {
                return ResourceManager.GetString("roomcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anahtar kelimeye göre ara.
        /// </summary>
        public static string searchbykeyword {
            get {
                return ResourceManager.GetString("searchbykeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gayrimenkul Arama.
        /// </summary>
        public static string searchestate {
            get {
                return ResourceManager.GetString("searchestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site içi arama.
        /// </summary>
        public static string searchinsite {
            get {
                return ResourceManager.GetString("searchinsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Sonuçları.
        /// </summary>
        public static string searchresult {
            get {
                return ResourceManager.GetString("searchresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektörler.
        /// </summary>
        public static string sectors {
            get {
                return ResourceManager.GetString("sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetler.
        /// </summary>
        public static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satılık.
        /// </summary>
        public static string sold {
            get {
                return ResourceManager.GetString("sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çözüm Ortaklarımız.
        /// </summary>
        public static string solutionpartners {
            get {
                return ResourceManager.GetString("solutionpartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrekare.
        /// </summary>
        public static string squaremeters {
            get {
                return ResourceManager.GetString("squaremeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi D..
        /// </summary>
        public static string taxoffice {
            get {
                return ResourceManager.GetString("taxoffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Tipi.
        /// </summary>
        public static string transactiontype {
            get {
                return ResourceManager.GetString("transactiontype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim.
        /// </summary>
        public static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizyonumuz.
        /// </summary>
        public static string vision {
            get {
                return ResourceManager.GetString("vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizyonumuz ve Misyonumuz.
        /// </summary>
        public static string visionmision {
            get {
                return ResourceManager.GetString("visionmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neden Biz?.
        /// </summary>
        public static string whyus {
            get {
                return ResourceManager.GetString("whyus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Yeri.
        /// </summary>
        public static string workplace {
            get {
                return ResourceManager.GetString("workplace", resourceCulture);
            }
        }
    }
}
